# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UTCWatchAppMvvmRx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UTCWatchAppMvvmRx
    pod 'RxSwift'
    pod 'RxCocoa'
end
